# name: testimg workflow

# on:
#   push:
#     branches:
#       - "master"

# jobs:
#   python-devops:
#     name: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'  # Use the appropriate Python version

#       - name: Run Python script and check module
#         run: |
#           python -c "
#           import os
#           import re
          
#           # List the contents of the repository
#           repo_name = '0x00-hello_world'
#           module = '1-compiler' 

          
#           repo_contents = os.popen(f'ls -R {repo_name}').read()
          
#           # Check if the folder exists using regex
#           if re.search(rf'{module}', repo_contents):
#               print('Found module')
#           else:
#               print('Module not found')
#           "


name: testimg workflow

on:
  push:
    branches:
      - "master"

jobs:
  python-devops:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Run Python script and check module
        run: |
          python -c "
          import re
          
          # List the contents of the repository
          repo_name = '0x00-hello_world'
          module = r'1-compiler' 

          
          # repo_contents = os.popen(f'ls -R {repo_name}').read()
          
          # Check if the folder exists using regex
          if re.search(module, repo_name):
              print('Found module')
          else:
              print('Module not found')
          "

