name: testimg workflow

on:
  push: 
    branches: 
      - "master"
    paths: 
      - 0x00-hello_world

jobs: 
  python-devops:
    name: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Run Python script
        run: |
          python -c "import re; print('Running Python script')"
