name: testimg worklow

on:
  push: 
    branches: "master"
    paths: 
      - 0x00-hello_world

jobs: 
  python-devops:
    name: test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: run-python-script
        run: |
          import re 
        
