name: testimg workflow

on:
  push:
    branches:
      - "master"

jobs:
  python-devops:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Run Python script and check module
        run: |
          python -c "
          import os
          import re
          
          # Define the folder and module to check for
          repo_name = '0x00-hello_world'
          module = '1-compiler'
          
          # Check if the repo_name folder exists
          if os.path.isdir(repo_name):
              print(f'Found folder {repo_name}')
              
              # Change directory to repo_name
              os.chdir(repo_name)
              
              # # List the contents of the current directory
              repo_contents = os.popen('ls -R').read()
              
              # Check if the module exists within the current directory
              if re.search(rf'{module}', repo_contents):
                  print(f'Found module {module}')
                  os.system('ls')
              else:
                  print(f'Module {module} not found')
          else:
              print(f'Folder {repo_name} not found')
          "
