name: testimg workflow

on:
  push:
    branches:
      - "master"

jobs:
  python-devops:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the appropriate Python version

    - name: Run Python script and check module
      run: |
        python -c "import re, os; print('Running Python script'); repo_name = 'alx-low_level_programming'; module = r'0x00-hello_world'; check_for_module = re.search(module, repo_name); if check_for_module: print('Found module'); else: print('Module not found'); os.system('exit 0')"  # Exit with success code 0
        if [[ $(git ls-files | grep -q "0x00-hello_world") ]]; then
          echo "Module directory found"
        else
          echo "Module directory not found"
        fi
