name: Test Vault Access

on:
  push:
    branches:
      - master

jobs:
  test-vault-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vault
        run: |
          # Manually specify the architecture for x64 (amd64) Linux runner
          ARCH=amd64

          # Manually specify the Vault version you want to install
          VAULT_VERSION=1.8.2

          # Download and install the specified Vault binary
          curl -fsSL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_${ARCH}.zip" -o vault.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/vault
          vault --version
        shell: bash

      - name: Authenticate with Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          # Authenticate with Vault using the provided token
          vault login $VAULT_TOKEN

      - name: Retrieve Secret from Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        run: |
          # Retrieve a secret from Vault and store it in a variable
          SECRET=$(vault kv get -field=pat https://vault-cluster-http-vault-0a859582.j.cloud.hashicorp.com/ui/vault/access/identity/entities/85f7a376-4a15-2fe6-1eca-c6ebc14e9b41/metadata?namespace=admin)
          echo "Vault Secret: $SECRET"

      - name: Use Secret for Testing
        run: |
          # Use the retrieved secret in your testing, for example:
          echo "Using Vault Secret: $SECRET"
