name: Test Vault Secret Access

on:
  push:
    branches:
      - master

jobs:
  test-secret-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Authenticate with Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          KUBE_NAMESPACE: development
    
        run: |
          VAULT_TOKEN=$(kubectl exec -n $KUBE_NAMESPACE pod-name -- vault write -field=token auth/kubernetes/login role=$VAULT_ROLE)
          echo "::set-env name=VAULT_TOKEN::$VAULT_TOKEN"

      - name: Retrieve Secret from Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        run: |
          SECRET=$(vault kv get -field=your-secret-path kv/myapp/credentials)
          echo "Vault Secret: $SECRET"

