name: Test Vault Access

on:
  push:
    branches:
      - master

jobs:
  test-vault-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vault
        run: |
          # Determine the GitHub Actions runner's architecture
          ARCH=$(uname -m)

          # Determine the latest Vault version
          VAULT_VERSION=$(curl -s https://releases.hashicorp.com/vault/ | grep -oE 'vault_[0-9]+\.[0-9]+\.[0-9]+' | tail -n1)

          # Download and install the correct Vault binary
          curl -fsSL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_${ARCH}.zip" -o vault.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/vault
          vault --version
        shell: bash

      - name: Authenticate with Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          # Authenticate with Vault using the provided token
          vault login $VAULT_TOKEN

      - name: Retrieve Secret from Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        run: |
          # Retrieve a secret from Vault and store it in a variable
          SECRET=$(vault kv get -field=<your-field-name> <your-secret-path>)
          echo "Vault Secret: $SECRET"

      - name: Use Secret for Testing
        run: |
          # Use the retrieved secret in your testing, for example:
          echo "Using Vault Secret: $SECRET"
