name: Terraform with AWS Secrets from Vault

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import Secrets from Vault
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportToken: true
          exportEnv: true
          secrets: |
            infrastructure/pipeline/aws/ access_key | AWS_ACCESS_KEY_ID ;
            infrastructure/pipeline/aws/ secret_key | AWS_SECRET_ACCESS_KEY ;

      - name: Echo AWS Access Key
        run: |
          echo "AWS Access Key ID: $AWS_ACCESS_KEY_ID"

      - name: Echo AWS Secret Key
        run: |
          echo "AWS Secret Access Key: $AWS_SECRET_ACCESS_KEY"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.7

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply --auto-approve
