name: Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          namespace: ${{ secrets.VAULT_NAMESPACE }}
          exportToken: true

      - name: Run Custom Command
        run: |
          # Run your custom command here
          # Replace 'kv-get secret/sample-secret' with the actual command you want to run
          kv-get secret/sample-secret
          
      - name: Verify secrets
        run: |
          if [ -z "$first-secret" ] || [ -z "$first-secret" ]; then
            echo "Error: Secrets are missing or empty."
            exit 1
          fi
